### ISSUE TITLE
[ feature request ] evaluating wall behind target

### ISSUE THREAD

**Issue by gzhegow1991** [No3371/SPT_ThatsLit#2]
Main idea of any stealth - be same color as wall behind you looking from enemy sight.
Brightess is a good option, but i dont know is possible at all to check texture at the line of sight to multiply detection koefficient, but then actually "no bush esp" could be disabled at all.

You're invisible exactly when the wall behind you is same camo color as you...
Night mode just make change saturation - so color of the camo and the wall becomes black if it is possible. Of course white wall could not become black - so you're visible at the night in front of white wall.

**Comment by No3371** [comment]
Not practically possible.

It a common idea and has came to my mind and been pondered on, and it also was brought up by multiple people before.

To simply put it, just think about how heavy it is just the 1 camera alone, now for every bot can see you in different direction you need to put a camera to their head and look at your direction.

**Comment by gzhegow1991** [comment]
eh(
thanks.
